name: Test Upload Logs Composite Action

on:
  workflow_dispatch:

env:
  GITHUB_BRANCH: ${{ github.ref_name }}
  SNOWFLAKE_LOG_TABLENAME: DBT_LOGS_TEST

  DBT_LOG_SNOWFLAKE_USERNAME_TEST: ${{ secrets.DBT_LOG_SNOWFLAKE_USERNAME_TEST }}
  DBT_LOG_SNOWFLAKE_PRIVATE_KEY_TEST: ${{ secrets.DBT_LOG_SNOWFLAKE_PRIVATE_KEY_TEST }}
  DBT_LOG_SNOWFLAKE_ACCOUNT_TEST: ${{ secrets.DBT_LOG_SNOWFLAKE_ACCOUNT_TEST }}
  DBT_LOG_SNOWFLAKE_WAREHOUSE_TEST: ${{ secrets.DBT_LOG_SNOWFLAKE_WAREHOUSE_TEST }}
  DBT_LOG_SNOWFLAKE_DATABASE_TEST: ${{ secrets.DBT_LOG_SNOWFLAKE_DATABASE_TEST }}
  DBT_LOG_SNOWFLAKE_SCHEMA_TEST: ${{ secrets.DBT_LOG_SNOWFLAKE_SCHEMA_TEST }}

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Set datetime
        run: echo "CURRENT_DATETIME=$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV

      - name: Create dummy dbt log
        run: |
          mkdir -p "logs/$CURRENT_DATETIME"
          echo '{"info": "test run", "data": "{}"}' > "logs/$CURRENT_DATETIME/dbt.log"

      - name: Upload logs
        if: ${{ !cancelled() }}
        uses:  KennyBalding-Tahola/test-logging-snow-with-key-user/.github/shraed-actions/upload-logs@main
